import logging
import os
from strands import Agent
from strands.models import BedrockModel
from mcp.client.streamable_http import streamablehttp_client
from strands.tools.mcp.mcp_client import MCPClient
from strands.multiagent.a2a import A2AServer
import uvicorn
from fastapi import FastAPI

logging.basicConfig(level=logging.INFO)

MCP_ENDPOINT = "https://mcp.platform.opentargets.org/mcp"
MODEL_ID = "global.anthropic.claude-sonnet-4-5-20250929-v1:0"

SYSTEM_PROMPT = """
You are a helpful AI assistant with knowledge of the OpenTargets platform, a comprehensive data
integration tool that supports systematic identification and prioritisation of potential
therapeutic drug targets. By integrating publicly available datasets including data
generated by the Open Targets experimental and informatics research programmes,
the Platform provides data and services to assist in the task of therapeutic
hypothesis building.
"""

def get_streamable_http_mcp_client() -> MCPClient:
    return MCPClient(lambda: streamablehttp_client(MCP_ENDPOINT))

mcp_client = get_streamable_http_mcp_client()

with mcp_client as client:
    tools = client.list_tools_sync()

strands_agent = Agent(
    model=BedrockModel(model_id=MODEL_ID),
    description="An AI assistant with deep knowledge of the OpenTargets platform for therapeutic target identification and prioritisation.",
    system_prompt=SYSTEM_PROMPT,
    tools=tools,
    callback_handler=None,
)

### A2A Server Content ###
#
# Use the complete runtime URL from environment variable, fallback to local
runtime_url = os.environ.get("AGENTCORE_RUNTIME_URL", "http://127.0.0.1:9000/")
logging.info(f"Runtime URL: {runtime_url}")
host, port = (
    "0.0.0.0",
    9000,
)  # nosec B104 — binds all interfaces intentionally; runs inside a container behind AgentCore Runtime proxy

# Pass runtime_url to http_url parameter AND use serve_at_root=True
a2a_server = A2AServer(
    agent=strands_agent,
    http_url=runtime_url,
    serve_at_root=True,  # Serves locally at root (/) regardless of remote URL path complexity
    enable_a2a_compliant_streaming=True,
)

app = FastAPI()


@app.get("/ping")
def ping():
    return {"status": "healthy"}


# AgentCore Runtime proxies GET requests as POST, so handle both
@app.post("/.well-known/agent-card.json")
def agent_card_post():
    return a2a_server.public_agent_card


app.mount("/", a2a_server.to_fastapi_app())

if __name__ == "__main__":
    uvicorn.run(app, host=host, port=port)
